; ─────────────────────────────────────────────────────────────────────────────
; dbus-mqtt-battery — Instance 42 — BMS 2 (adresse RS485 0x02)
; Copier vers : /data/etc/dbus-mqtt-battery-42/config.ini
; GitHub : https://github.com/mr-manuel/venus-os_dbus-mqtt-battery
; ─────────────────────────────────────────────────────────────────────────────

[DEFAULT]
logging = WARNING
device_name = MQTT Battery 360Ah
device_instance = 142
; Timeout déconnexion si aucun message reçu (secondes) — 0 = désactivé
timeout = 15

[MQTT]
broker_address = 192.168.1.120
broker_port = 1883
topic = santuario/bms/2/venus
;username = myuser
;password = mypassword

[TIME_TO_GO]
enabled = 1
soc = 10
recalculate_every = 60
