# =============================================================================
# Grafana — Provisioning datasource InfluxDB 2.x (Flux)
# =============================================================================

apiVersion: 1

deleteDatasources:
  - name: InfluxDB-DalyBMS
    orgId: 1

datasources:
  - name: InfluxDB-DalyBMS
    type: influxdb
    uid: influxdb-dalybms-flux
    access: proxy
    url: http://dalybms-influxdb:8086
    isDefault: true
    editable: true
    orgId: 1

    jsonData:
      version: Flux
      organization: santuario
      defaultBucket: daly_bms
      timeInterval: "10s"

    secureJsonData:
      token: "TGEh4wl5TE7SEeJd7GDdyjDebo48xEJaD63MKbgdNhLz54-AWLxWtEBxoAqIEPd9KOucM_kpJGtvFu3oZ98KeQ=="
