# =============================================================================
# Grafana — Provisioning datasource InfluxDB 2.x (Flux)
# =============================================================================

apiVersion: 1

deleteDatasources:
  - name: InfluxDB-DalyBMS
    orgId: 1

datasources:
  - name: InfluxDB-DalyBMS
    type: influxdb
    uid: influxdb-dalybms
    access: proxy
    url: http://dalybms-influxdb:8086
    isDefault: true
    editable: true
    orgId: 1

    jsonData:
      version: Flux
      organization: "${INFLUX_ORG}"
      defaultBucket: "${INFLUX_BUCKET}"
      timeInterval: "10s"

    secureJsonData:
      token: "${INFLUX_TOKEN}"
